name: dart_frog_cors
description: CORS middleware for dart_frog.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
dependencies:
  dart_frog: ^0.3.2
